In [1]:
import torch

In [2]:
rank1_t = torch.rand((10))
rank2_t = torch.rand((5, 5))
rank3_t = torch.rand((5, 5, 2))

In [3]:
rank1_t, rank1_t.shape

(tensor([0.6493, 0.6670, 0.2945, 0.4771, 0.3879, 0.6281, 0.9099, 0.7811, 0.9776,
         0.5257]),
 torch.Size([10]))

In [7]:
rank2_t, rank2_t.shape

(tensor([[0.2059, 0.5694, 0.2947, 0.0068, 0.5810],
         [0.7795, 0.9245, 0.8283, 0.0886, 0.4958],
         [0.5320, 0.8959, 0.0215, 0.2566, 0.1724],
         [0.2672, 0.3820, 0.0533, 0.7017, 0.7364],
         [0.3024, 0.9869, 0.1476, 0.7994, 0.8638]]),
 torch.Size([5, 5]))

In [8]:
rank3_t, rank3_t.shape

(tensor([[[0.3399, 0.0349],
          [0.7521, 0.0887],
          [0.3781, 0.2821],
          [0.0029, 0.2586],
          [0.8463, 0.6247]],
 
         [[0.8220, 0.3879],
          [0.7420, 0.4603],
          [0.5137, 0.5057],
          [0.1467, 0.7230],
          [0.9477, 0.8444]],
 
         [[0.5125, 0.1029],
          [0.8217, 0.1964],
          [0.5994, 0.9645],
          [0.1527, 0.0902],
          [0.9948, 0.7729]],
 
         [[0.3224, 0.5847],
          [0.6585, 0.3487],
          [0.6036, 0.0825],
          [0.7418, 0.6563],
          [0.8691, 0.4398]],
 
         [[0.1386, 0.5273],
          [0.7236, 0.8541],
          [0.1680, 0.5640],
          [0.7103, 0.1916],
          [0.0485, 0.5787]]]),
 torch.Size([5, 5, 2]))

In [1]:
import torch

In [2]:
x = torch.Tensor([-10, 10, 8]).requires_grad_()

In [3]:
sigmoid = 1 / (1 + torch.exp(-x))

In [4]:
sigmoid

tensor([4.5398e-05, 9.9995e-01, 9.9966e-01], grad_fn=<MulBackward0>)

In [6]:
s = sigmoid.sum()

In [7]:
s

tensor(1.9997, grad_fn=<SumBackward0>)

In [8]:
s.backward()

In [9]:
x.grad

tensor([4.5396e-05, 4.5396e-05, 3.3524e-04])

In [21]:
A = torch.Tensor([[1, 2, -3], [4, 5, 10]])
B = torch.Tensor([[10, 11, -2], [13, -3, 8]])

In [22]:
a = 10
B + a

tensor([[20., 21.,  8.],
        [23.,  7., 18.]])

In [23]:
A.T

tensor([[ 1.,  4.],
        [ 2.,  5.],
        [-3., 10.]])

In [24]:
B.T

tensor([[10., 13.],
        [11., -3.],
        [-2.,  8.]])

In [25]:
A = torch.Tensor([[1, 2, 3], [4, 5, 6]])
B = torch.Tensor([[10, 11], [-2, 0], [1, -3]])
A @ B

tensor([[ 9.,  2.],
        [36., 26.]])

In [26]:
torch.norm(A), torch.norm(B)

(tensor(9.5394), tensor(15.3297))